# Generated by Django 4.0.5 on 2022-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=15)),
                ('L_name', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
    ]
